package com.mcwbalance.node;

import com.mcwbalance.result.ResultFlow;
import com.mcwbalance.result.ResultLevel;
import com.mcwbalance.result.ResultStorageVolume;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

/**
 * TODO - NOT COMPLETED
 * Holds and handles all the results from a single climate scenario run for a node
 * @author alex
 */
public class ResultNode {
    
    public ResultLevel resultWaterLevel;
    public ResultLevel resultSolidsLevel;
    
    public ResultStorageVolume resultTotalVolume;
    public ResultStorageVolume resultPondVolume;
    
    public ResultFlow resultSolidsInflow;
    
    public ResultFlow resultRunoff[];
    public ResultFlow resultDirectPrecip;
    public ResultFlow resultEvaporation;
    public ResultFlow resultSeepage;
    
    private final String[] landCovers; 
    private final int nodeIndex;
    private final String nodeName;
    private final String scenario;
        
    /**
     * Holds and handles all the results from a single climate scenario run for a node
     * @param nodeIndex index of node within NodList
     * @param nodeName String name of node for reporting
     * @param scenario String name of scenario for reporting
     * @param landCovers String name of land covers within Runoff Coefficients for reporting
     * @param duration duration of run in days, determines length of result arrays
     */
    public ResultNode(int nodeIndex, String nodeName, String scenario, String[] landCovers, int duration) {
        
        this.landCovers = landCovers;
        this.nodeIndex = nodeIndex;
        this.nodeName = nodeName;
        this.scenario = scenario;
        resultWaterLevel = new ResultLevel(duration, nodeName + " Water Level");
        resultSolidsLevel = new ResultLevel(duration, nodeName + " Solids Level");
        resultSolidsInflow = new ResultFlow(duration, nodeName + " Solids Inflow");
        
        resultTotalVolume = new ResultStorageVolume(duration, nodeName + " Total Stored Volume");
        
        resultPondVolume = new ResultStorageVolume(duration, nodeName + " Pond Volume");
        
        resultRunoff = new ResultFlow[landCovers.length];
        for (int i = 0; i < resultRunoff.length; i++) {
            resultRunoff[i] = new ResultFlow(duration, nodeName + landCovers[i]);
        }
        resultDirectPrecip = new ResultFlow(duration, nodeName + " Direct Precip");
        
        resultEvaporation = new ResultFlow(duration, nodeName + " Evaporation");
        resultSeepage = new ResultFlow(duration, nodeName + " Seepage");
    }
    
    /**
     * TODO Used for generating a CSV representation of the Result
     *
     * @return
     */
    public String getCSVString() {
        return "ResultNode.java getCSVString() method not implemented";
    }

    /**
     * TODO Used for generating a XML representation of the Result for Saving
     * only Not to be used for Export to XML Spreadsheet
     *
     * @param doc XML document that Element will be appended to
     * @return XML representation of the Result for Saving only, not for XML
     * Spreadsheets
     */
    public Element getXMLElement(Document doc) {
        Element ele = doc.createElement("NodeResult");
        ele.setAttribute("Status", "ResultNode.java getXMLElement() method not implemented");
        return ele;
    }

    /**
     * TODO Used for generating a XML representation of the Result for Exporting
     * to Spreadsheet
     *
     * @param doc XML document that Element will be appended to
     * @return XML representation of the Result for Saving only, not for XML
     * Spreadsheets
     */
    public Element getXMLElementSS(Document doc) {
        Element ele = doc.createElement("NodeResult");
        ele.setAttribute("Status", "ResultNode.java getXMLElementSS() method not implemented");
        return ele;
    }
    /**
     * TODO - Not Completed
     * Loads result in from a save file XML element, this will not work with a Spreadsheet XML
     * @see getXMLElement
     * @param ele XML representation of the Result generated by getXMLElement
     * 
     */
    public void loadXMLElement(Element ele) {
        System.err.println("ResultNode.java loadXMLElement() method not implemented");
    }
    
    /**
     * Used for getting list of land covers based on Runoff Coefficients table
     * @return list of land covers
     */
    public String[] getlandCovers(){
        return landCovers;
    } 
    
    /**
     * Used for getting NODList index of node
     * @return NODList index of node
     */
    public int getnodeIndex(){
        return nodeIndex;
    }
    
    /**
     * Used for getting name of node
     * @return Name of Node
     */
    public String getnodeName(){
        return nodeName;
    }
    
    /**
     * Used for getting name of scenario
     * @return Name of Climate Scenario
     */
    public String getscenario(){
        return scenario;
    }
}
